name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: "18"
    - name: Install & Build
      run: |
        npm install
        npm run build
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ui-bundle.zip
    #     path: build/ui-bundle.zip
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/ui-bundle.zip
